---
title: "flat_check_data.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

```{r function-check_plus_in_primary_fur_color}
# check_plus_in_primary_fur_color

#' Check the values of primary fur color
#'
#' @param primary_fur_color Character. A vector with the primary fur color.
#' @return a vector of logicals
#' @importFrom stringr str_detect
#' @export
check_plus_in_primary_fur_color <- function(primary_fur_color) {
  if(isFALSE(is.character(primary_fur_color))){
    stop("primary_fur_color must be a character")
  }
  colors_are_ok <- (!str_detect(string = primary_fur_color, pattern = "\\+"))
  return(colors_are_ok)
}
```

```{r developement-check_plus_in_primary_fur_color}
library(stringr)
```

```{r example-check_plus_in_primary_fur_color}
primary_fur_color_ok <- c("Black", "Black", "Cinnamon", NA)
primary_fur_color_nok <- c("Black", "Black+Cinnamon", "Cinnamon", NA)
primary_fur_color_error <- c(2, 3)

check_plus_in_primary_fur_color(primary_fur_color_ok)
check_plus_in_primary_fur_color(primary_fur_color_nok)
#check_plus_in_primary_fur_color(primary_fur_color_error)

```

```{r tests-check_plus_in_primary_fur_color}

primary_fur_color_ok <- c("Black", "Black", "Cinnamon", NA)
primary_fur_color_nok <- c("Black", "Black+Cinnamon", "Cinnamon", NA)
primary_fur_color_error <- c(2, 3)

test_that("check_plus_in_primary_fur_color detects the '+' character", {

  expect_equal(
    object = check_plus_in_primary_fur_color(primary_fur_color_nok),
    expected = c(TRUE, FALSE, TRUE, NA)
  )
  
    expect_equal(
    object = check_plus_in_primary_fur_color(primary_fur_color_ok),
    expected = c(TRUE, TRUE, TRUE, NA)
  )
})

  test_that("check_plus_in_primary_fur_color returns error if not a char", {

    expect_error(object = check_plus_in_primary_fur_color(primary_fur_color_error),
                 regexp = "primary_fur_color must be a character")
})

```

# check_presence_of_required_columns
    
```{r development-check_presence_of_required_columns}
library(squirrels)
```
  
```{r function-check_presence_of_required_columns}
#' Verify if the required columns are present in the dataset
#'
#' long, lat and primary_fur_color are required
#' 
#' @param df Data frame. A dataset with squirrels data.
#' @return a boolean
#'
#' @export
check_presence_of_required_columns <- function(df) {
  required_columns_are_present <- all(
    c("primary_fur_color", "long", "lat") %in% names(df)
  )

  if (isFALSE(required_columns_are_present)) {
    stop("The dataset does not contain the required columns")
  }

  return(required_columns_are_present)}
```
  
```{r example-check_presence_of_required_columns}
  check_presence_of_required_columns(data_demo_squirrels)
```

```{r tests-check_presence_of_required_columns}
test_that("check_presence_of_required_columns", {
  expect_true(inherits(check_presence_of_required_columns, "function")) 
})

test_that("squirrels sample dataset in inst contains all initial 200 rows", {
  expect_equal(
    object = nrow(read.csv(system.file('nyc_squirrels_sample.csv', package = "squirrels"))),
    expected = 200
  )
})

```
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_check_data.Rmd", vignette_name = "Check data")
```

