---
title: "flat_export_results.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# save_as_csv
    
```{r development-save_as_csv}


# You can prepare the code of the save_as_csv() function here
```
  
```{r function-save_as_csv}
#' Sauvegarde d'un df en csv
#' 
#' @param df df a exporter
#' @param path chemin de sortie
#' @return le chemin de sortie
#' 
#' @export
save_as_csv <- function(df, path){
  
  write_csv2(df, file = path)
  
  return(path)
    
}
```
  
```{r example-save_as_csv}
library(squirrels)
library(readr)
save_as_csv(df = data_demo_squirrels, './test.csv')
```
  
```{r tests-save_as_csv}
test_that("save_as_csv works", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  fichier_temp <- file.path(mon_dossier_temp_aleatoire, "written_csv.csv")
  
  save_as_csv(df = data_demo_squirrels, path = fichier_temp)
  
  # On vérifie que le fichier a bien été écrit en sortie
  expect_true(file.exists(fichier_temp))
  # On vérifie que la taille du fichier est non nulle
  expect_true(file.info(fichier_temp)$size > 0)
  
  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})

test_that("written file is a dataframe", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  fichier_temp <- file.path(mon_dossier_temp_aleatoire, "written_csv.csv")
  
  save_as_csv(df = data_demo_squirrels, path = fichier_temp)
  
  # On vérifie que le fichier a bien été écrit en sortie
  expect_true(inherits(read_csv2(fichier_temp), "data.frame"))

  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})

test_that("written filename has .csv extension", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  # TBC... 

  expect_true()

  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_export_results.Rmd", vignette_name = "Go further")
```

