# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("save_as_csv works", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  fichier_temp <- file.path(mon_dossier_temp_aleatoire, "written_csv.csv")
  
  save_as_csv(df = data_demo_squirrels, path = fichier_temp)
  
  # On vérifie que le fichier a bien été écrit en sortie
  expect_true(file.exists(fichier_temp))
  # On vérifie que la taille du fichier est non nulle
  expect_true(file.info(fichier_temp)$size > 0)
  
  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})

test_that("written file is a dataframe", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  fichier_temp <- file.path(mon_dossier_temp_aleatoire, "written_csv.csv")
  
  save_as_csv(df = data_demo_squirrels, path = fichier_temp)
  
  # On vérifie que le fichier a bien été écrit en sortie
  expect_true(inherits(read_csv2(fichier_temp), "data.frame"))

  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})

test_that("written filename has .csv extension", {
  
  mon_dossier_temp_aleatoire <- tempfile(pattern = "test_save_as_csv")
  dir.create(mon_dossier_temp_aleatoire)
  # TBC... 

  expect_true()

  unlink(mon_dossier_temp_aleatoire, recursive = TRUE)
  
})
