# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.


primary_fur_color_ok <- c("Black", "Black", "Cinnamon", NA)
primary_fur_color_nok <- c("Black", "Black+Cinnamon", "Cinnamon", NA)
primary_fur_color_error <- c(2, 3)

test_that("check_plus_in_primary_fur_color detects the '+' character", {

  expect_equal(
    object = check_plus_in_primary_fur_color(primary_fur_color_nok),
    expected = c(TRUE, FALSE, TRUE, NA)
  )
  
    expect_equal(
    object = check_plus_in_primary_fur_color(primary_fur_color_ok),
    expected = c(TRUE, TRUE, TRUE, NA)
  )
})

  test_that("check_plus_in_primary_fur_color returns error if not a char", {

    expect_error(object = check_plus_in_primary_fur_color(primary_fur_color_error),
                 regexp = "primary_fur_color must be a character")
})

