# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_presence_of_required_columns", {
  expect_true(inherits(check_presence_of_required_columns, "function")) 
})

test_that("squirrels sample dataset in inst contains all initial 200 rows", {
  expect_equal(
    object = nrow(read.csv(system.file('nyc_squirrels_sample.csv', package = "squirrels"))),
    expected = 200
  )
})

