# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

# check_plus_in_primary_fur_color

#' Check the values of primary fur color
#'
#' @param primary_fur_color Character. A vector with the primary fur color.
#' @return a vector of logicals
#' @importFrom stringr str_detect
#' @export
#' @examples
#' primary_fur_color_ok <- c("Black", "Black", "Cinnamon", NA)
#' primary_fur_color_nok <- c("Black", "Black+Cinnamon", "Cinnamon", NA)
#' primary_fur_color_error <- c(2, 3)
#'
#' check_plus_in_primary_fur_color(primary_fur_color_ok)
#' check_plus_in_primary_fur_color(primary_fur_color_nok)
#' #check_plus_in_primary_fur_color(primary_fur_color_error)
#'
check_plus_in_primary_fur_color <- function(primary_fur_color) {
  if(isFALSE(is.character(primary_fur_color))){
    stop("primary_fur_color must be a character")
  }
  colors_are_ok <- (!str_detect(string = primary_fur_color, pattern = "\\+"))
  return(colors_are_ok)
}
