# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand # nolint: line_length_linter.

#' Sauvegarde d'un df en csv
#' 
#' @param df df a exporter
#' @param path chemin de sortie
#' @return le chemin de sortie
#' 
#' @export
#' @examples
#' library(squirrels)
#' library(readr)
#' save_as_csv(df = data_demo_squirrels, './test.csv')
save_as_csv <- function(df, path){
  
  write_csv2(df, file = path)
  
  return(path)
    
}
