# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand # nolint: line_length_linter.

#' Sauvegarde d'un df en csv
#' 
#' @param df df a exporter
#' @param path chemin de sortie
#' @return le chemin de sortie
#' @importFrom tools file_ext
#' @importFrom readr write_csv2
#' @export
#' @examples
#' mon_dossier_temp <- tempfile(pattern = "savecsv")
#' dir.create(mon_dossier_temp)
#'
#' save_as_csv(df = iris, path = file.path(mon_dossier_temp, "output.csv"))
#'
#' unlink(mon_dossier_temp, recursive = TRUE)
#'
save_as_csv <- function(df, path){
  
  if (isFALSE(is.data.frame(df))) {
    stop("df is not a dataframe")
  }
  
  if (isFALSE(file_ext(path) == "csv")) {
    stop("path does not have extension csv")
  }
  
  if (isFALSE(dir.exists(dirname(path)))) {
    stop("path does not exist")
  }
  
  write_csv2(df, file = path)
  
  return(path)
    
}
